easy_admin:
    entities:
        Game:
          class: AppBundle\Entity\Game
          label: 'Games'
          form:
              fields:
                  - { property: 'startedAt', type: 'datetime', type_options: { 'widget': 'single_text', 'attr': { 'class': 'datepicker'} } }
                  - { property: 'homeTeam', type: 'easyadmin_autocomplete', type_options: { class: 'AppBundle\Entity\Team' } }
                  - { property: 'homeScore', type: 'number' }
                  - { property: 'guestTeam', type: 'easyadmin_autocomplete', type_options: { class: 'AppBundle\Entity\Team' } }
                  - { property: 'guestScore', type: 'number' }
                  - stadium
                  - { property: 'status', type: 'choice', type_options: { choices: { 'Current': 'C', 'Future': 'F', 'Past': 'P' } } }
          list:
              fields:
                  - 'id'
                  - 'homeTeam'
                  - 'guestTeam'
                  - 'startedAt'
                  - 'status'
                  - 'stadium'
