easy_admin:
    entities:
        Game:
          class: AppBundle\Entity\Game
          label: 'Games'
          form:
          list:
              fields:
                  - 'id'
                  - 'homeTeam'
                  - 'guestTeam'
                  - 'startedAt'
                  - 'status'
                  - 'stadium'
              fields:
                  - { property: 'startedAt', type: 'datetime' }
                  - { property: 'homeTeam', type: 'easyadmin_autocomplete', type_options: { class: 'AppBundle\Entity\Team' } }
                  - { property: 'homeScore', type: 'number' }
                  - { property: 'guestTeam', type: 'easyadmin_autocomplete', type_options: { class: 'AppBundle\Entity\Team' } }
                  - { property: 'guestScore', type: 'number' }
                  - { property: 'stadium', type: 'text' }
                  - { property: 'status', type: 'text' }